steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "Dockerfile.frontend"
      - "-t"
      - "asia-south1-docker.pkg.dev/$PROJECT_ID/govprep/frontend:latest"
      - "."

images:
  - "asia-south1-docker.pkg.dev/$PROJECT_ID/govprep/frontend:latest"

options:
  machineType: "E2_HIGHCPU_8"

timeout: "1200s"
