steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull asia-south1-docker.pkg.dev/$PROJECT_ID/govprep/backend:latest || true

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--cache-from"
      - "asia-south1-docker.pkg.dev/$PROJECT_ID/govprep/backend:latest"
      - "-f"
      - "Dockerfile.backend"
      - "-t"
      - "asia-south1-docker.pkg.dev/$PROJECT_ID/govprep/backend:latest"
      - "."

images:
  - "asia-south1-docker.pkg.dev/$PROJECT_ID/govprep/backend:latest"

options:
  machineType: "E2_HIGHCPU_8"

timeout: "2400s"
